RI-3892 - Tree View Improvements
RedisInsight/RedisInsight pull request #1488
Opened 2022-12-08 07:42 UTC by nmammadli

2022-12-08 07:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisInsight/RedisInsight?pullRequest=1488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisInsight/RedisInsight?pullRequest=1488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisInsight/RedisInsight?pullRequest=1488) it.</sub>

2022-12-08 07:56 UTC, ofersteinberg commented on tests/e2e/pageObjects/browser-page.ts
> +
Redundant space

2022-12-08 07:56 UTC, ofersteinberg commented on tests/e2e/pageObjects/browser-page.ts
> +    * It will go to mobile -> 2 -> keys
IMO it's not required. We generally do that where we have "complexity."
@vlad-dargel - WDYT?

2022-12-08 07:56 UTC, ofersteinberg commented on tests/e2e/pageObjects/cli-page.ts
> +        let word = common.generateWord(10);
Could be `const`

2022-12-08 07:56 UTC, ofersteinberg commented on tests/e2e/pageObjects/cli-page.ts
> +        let index = 'idx:' + word;
1. Could be `const`
2. Better method: 
```
 `idx: ${word}`
```

2022-12-08 07:56 UTC, ofersteinberg commented on tests/e2e/tests/critical-path/tree-view/tree-view-improvements.e2e copy.ts
> +let index: string;
Please remove the redundant spaces

2022-12-08 12:10 UTC, vlad-dargel requested changes

2022-12-08 12:10 UTC, vlad-dargel commented on tests/e2e/tests/critical-path/tree-view/tree-view-improvements.e2e copy.ts
> +    });
Don't see these tests:
1) "The folder without any patterns selected and the list of keys is displayed when there is a folder without any patterns"
![image](https://user-images.githubusercontent.com/90257586/206441449-b6cf7faf-9b2a-4a03-9949-5421eb6ee691.png)
2) The folder without any namespaces is selected (if exists) when folder does not exist after search/filter
![image](https://user-images.githubusercontent.com/90257586/206441846-d49a944a-813c-40d1-95a0-c35b81fb71d7.png)
3) The first folder with namespaces is expanded and selected when folder and folder without any namespaces does not exist after search/filter
(it is when one folder is opened and you search for key from other folder - other folder should be opened after such search)
4) The previously selected folder is preselected when key does not exist after keys refresh (you need to select one folder, then delete any key from this folder by CLI and click refresh - verify that the same folder still selected)

2022-12-13 16:19 UTC, vlad-dargel reviewed
Looks good
just need to map all verifications (.expect and verifyKeysDisplayedInTheList) with tests from checklist.
you can use names both from Scenario and Checklist column
![image](https://user-images.githubusercontent.com/90257586/207386889-092b9132-89bb-48ab-a3bf-3d5878884641.png)

2022-12-13 16:19 UTC, vlad-dargel commented on tests/e2e/tests/critical-path/tree-view/tree-view-improvements.e2e.ts
> +    })('Tree view preselected folder, Filterred Tree view preselected folder, Refreshed Tree view preselected folder, Search capability Filterred Tree view preselected folder', async t => {
too long name
you can name it just 'Tree view preselected folder'

and below before each ".expect/verify" in test add comment with test from checklist (to be understandable what each verification step actually checks)

2022-12-13 16:19 UTC, vlad-dargel commented on tests/e2e/tests/critical-path/tree-view/tree-view-improvements.e2e.ts
> +    })('Refreshed Tree view preselected folder, Filterred Tree view preselected folder', async t => {
the name is the same as part of the 1st test name from this fixture

2022-12-13 16:23 UTC, vlad-dargel commented on tests/e2e/tests/critical-path/tree-view/tree-view-improvements.e2e.ts
> +            Selector('[role="rowgroup"]').find('div').withText('No results found.').visible)
just use here
`await t.expect(browserPage.keyListTable.textContent).notContains('No results found.', 'Key is not found message still displayed');`

2022-12-14 08:49 UTC, vlad-dargel approved these changes

2022-12-14 08:58 UTC, merged