Be/feature/CR-28
RedisInsight/RedisInsight pull request #3314
Opened 2024-04-25 18:35 UTC by nelsonwellsredis

2024-04-26 13:01 UTC, arthosofteq requested changes
looks good! thanks
Please address small comments

2024-04-26 13:02 UTC, arthosofteq commented
Also seems like you've broke integration tests :)

2024-04-26 20:07 UTC, nelsonwellsredis commented on redisinsight/api/test/helpers/server.ts
> +    app.useWebSocketAdapter(new SessionMetadataAdapter(app));
@arthosofteq this is the line of code I had to add for the BE integration tests to pass

2024-05-07 21:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisInsight/RedisInsight?pullRequest=3314) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RedisInsight/RedisInsight?pullRequest=3314) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nelsonwellsredis<br/>:x: arthosofteq<br/><hr/>**arthosofteq** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisInsight/RedisInsight?pullRequest=3314) it.</sub>

2024-05-30 13:19 UTC, merged