#RI-2076 - preparing the plugin sdk for npm, update docs
RedisInsight/RedisInsight pull request #34
Opened 2021-11-23 08:54 UTC by romansergeenkosofteq

2021-11-23 12:09 UTC, ViktorStarostenko submitted a review, later dismissed

2022-02-16 13:18 UTC, ViktarStarastsenka requested changes

2022-02-16 14:04 UTC, romansergeenkosofteq commented on redisinsight/ui/src/packages/redisinsight-plugin-sdk/LICENSE
> +Copyright (c) 2022 Redis
done

2022-02-18 09:11 UTC, ViktarStarastsenka approved these changes

2022-02-18 09:42 UTC, merged